### ISSUE TITLE
Add GraphAPI application Application.ReadWrite.OwnedBy role access to OIDC service principal

### ISSUE THREAD

**Issue by animal77** [ned1313/terraform-azuread-github_oidc#14]
Motivation:

Suppose the SP created here is running Terraform to create a static web app (SWA). Further suppose that SWA requires custom authentication to be configured as described [here](https://learn.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad%2Cinvitations). The TL;DR of how this is done is:

1. Creating a new App Registration
2. Save the Application (client) ID for the Microsoft Entra app registration.
3. Save the client secret for the Microsoft Entra app registration. 
4. Configure two parameters in SWA's Application Settings `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`
6. Reference these settings in `staticwebapp.config.json` of the SWA
7. Enjoy authentication via AD for users of the SWA

A sample terraform script to accomplish 1-4 above is as follows:
```hcl
# Create SP 
resource "azuread_application_registration" "my_static_frontend" {
  display_name = "My Static Frontend"
  description  = "My cool application"
}

# Create password
resource "azuread_application_password" "my_static_frontend" {
  application_id = azuread_application_registration.my_static_frontend.id
}

# create the SWA
resource "azurerm_static_site" "my_static_frontend" {
  name                = "stapp-my-frontend-${local.name_suffix}"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  app_settings = {
    "AZURE_CLIENT_ID"           = azuread_application_registration.my_static_frontend.client_id
    "AZURE_CLIENT_SECRET"       = azuread_application_password.my_static_frontend.value
  }
  tags = local.common_tags
}
```

This script fails because the OIDC SP has insufficient permissions to create the application. It needs [Microsoft Graph's Application.ReadWrite.OwnedBy](https://learn.microsoft.com/en-us/graph/permissions-reference#applicationreadwriteownedby).  Note that `Application.ReadWrite.All` would do but we prefer this in keeping with the principle of using the least required privilege.

**Comment by ned1313** [comment]
Thanks for submitting the issue! I think this suggestion falls outside the scope of the module. The goal of the module is to create the necessary service principal and federated identities and not grant permissions. Granting permissions should be the role of the root module that invokes this module.
