### ISSUE TITLE
KiCS verification fails without output description

### ISSUE THREAD

**Issue by robinmordasiewicz** [ned1313/terraform-azuread-github_oidc#7]
Output Without Description, Severity: INFO, Results: 4
  Description: All outputs should contain a valid description.
  Platform: Terraform
  Learn more about this vulnerability: https://docs.kics.io/latest/queries/terraform-queries/common/59312e8a-a64e-41e7-a252-618533dd1ea8

**Comment by ned1313** [comment]
Resolved with PR #6 
New release cut v1.2.2
